#!/bin/python3

import math
import os
import random
import re
import sys

def checkMagazine(magazine, note):
    dict = {}
    no = 0
    if len(note) > len(magazine):
        no = 1
        print("No")
    else:
        for word in magazine:
            if word in dict :
                dict[word] += 1
            else:
                dict[word] = 1      
        for word in note:
            if word in dict and dict[word] > 0:
                dict[word] -= 1
            else:
                no = 1
                print("No")
                break
            
    if no == 0:  
        print("Yes")

if __name__ == '__main__':
    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    magazine = input().rstrip().split()

    note = input().rstrip().split()

    checkMagazine(magazine, note)

    


